### ISSUE TITLE
Using middleware error

### ISSUE THREAD

**Issue by oasin** [jarle/remix-adonisjs#72]
When i add the ["web"] middleware to the route there is an error displayed in the console
 
Failed to fetch manifest patches SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by jarle** [comment]
I think this might be caused by the requests to `/__manifest` failing. Could you try adding the entry `/__manifest` to your `openRoutes` in `auth_middleware.ts` and see if it works?

**Comment by oasin** [comment]
Solved it.. ❤️
